### ISSUE TITLE
Couldn't find OutOfBalanceException.cs

### ISSUE THREAD

**Issue by namit2saxena** [PavloPaitak1998/ParkingConsoleApp#15]
I just cloned your repository to know more about your project. When I am building the project I am getting the following error: 
`'E:\Repo\ParkingConsoleApp\ParkingConsoleApp\ParkingConsoleApp\OutOfBalanceException.cs' could not be found.	`

Any help will be appreciated, thank you!

**Comment by PavloPaitak** [comment]
In the Exceptions.cs, there are all exception classes

**Comment by PavloPaitak** [comment]
Try also to create a  new console app and just paste all clases
